# Generated by Django 6.0 on 2025-12-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Student Testimonial', 'verbose_name_plural': 'Student Testimonials'},
        ),
        migrations.AddField(
            model_name='testimonial',
            name='company',
            field=models.CharField(blank=True, help_text='Company/School name', max_length=100),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='graduation_year',
            field=models.IntegerField(blank=True, help_text='Year student graduated', null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='verified',
            field=models.BooleanField(default=False, help_text='Verified testimonial'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=5, help_text='Student rating (1-5 stars)'),
        ),
    ]
