# Generated by Django 6.0 on 2025-12-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0002_alter_testimonial_options_testimonial_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='user',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='instructors/'),
        ),
    ]
