# Generated by Django 6.0 on 2025-12-14 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_app', '0004_alter_banner_options_banner_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='facebook',
            new_name='telegram',
        ),
    ]
